name       : haskell-zlib
version    : 0.6.3.0
release    : 8
source     :
    - https://hackage.haskell.org/package/zlib-0.6.3.0/zlib-0.6.3.0.tar.gz : 9eaa989ad4534438b5beb51c1d3a4c8f6a088fdff0b259a5394fbf39aaee04da
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a pure interface for compressing and decompressing streams of data
description: |
    This package provides a pure interface for compressing and decompressing streams of data
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
