name       : haskell-zlib
version    : 0.6.2
release    : 6
source     :
    - https://hackage.haskell.org/package/zlib-0.6.2/zlib-0.6.2.tar.gz : 0dcc7d925769bdbeb323f83b66884101084167501f11d74d21eb9bc515707fed
license    : BSD-3-Clause
component  : programming.haskell
summary    : This package provides a pure interface for compressing and decompressing
    streams of data
description: |
    This package provides a pure interface for compressing and decompressing streams of data
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
