name       : haskell-zlib
version    : 0.6.1.1
release    : 1
source     :
    - http://hackage.haskell.org/package/zlib-0.6.1.1/zlib-0.6.1.1.tar.gz : c5f5b4285473657a7997d74f7642f3e7bda40f92c3c5d49471a899e27a4ba735
license    : BSD-3-Clause
component  : programming
summary    : This package provides a pure interface for compressing and decompressing streams of data
description: |
    This package provides a pure interface for compressing and decompressing streams of data
builddeps  :
    - ghc
setup      : |
    ghc -threaded --make Setup
    ./Setup configure --ghc \
                      --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 zlib-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/zlib-$version.conf
    rm -f $installdir/usr/lib64/$GHCV/zlib-$version/*.a